add_library(krr_usd_sdk INTERFACE)
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	message(FATAL_ERROR "The pinned USD SDKs use the release CRT; select RelWithDebInfo for debugging")
endif()
if(KRR_ENABLE_HYDRA)
	if(NOT KRR_BLENDER_SDK)
		if(NOT "$ENV{KRR_BLENDER_SDK}" STREQUAL "")
			set(KRR_BLENDER_SDK "$ENV{KRR_BLENDER_SDK}" CACHE PATH "Development libraries matching the Blender host" FORCE)
		elseif(EXISTS "${KRR_RENDER_ROOT}/build/blender-5.2/sdk/usd/include/pxr/pxr.h")
			set(KRR_BLENDER_SDK "${KRR_RENDER_ROOT}/build/blender-5.2/sdk" CACHE PATH "Development libraries matching the Blender host" FORCE)
		endif()
	endif()
	set(_usd_include "${KRR_BLENDER_SDK}/usd/include")
	if(NOT EXISTS "${_usd_include}/pxr/pxr.h")
		message(FATAL_ERROR "Set KRR_BLENDER_SDK to the matching Blender 5.2.2 development bundle (selected: '${KRR_BLENDER_SDK}')")
	endif()
	file(READ "${_usd_include}/pxr/pxr.h" _usd_header)
	if(NOT _usd_header MATCHES "pxrBlender_v26_03__pxrReserved__")
		message(FATAL_ERROR "The Hydra profile requires Blender 5.2.2's patched USD SDK")
	endif()
	target_include_directories(krr_usd_sdk SYSTEM INTERFACE
		"${_usd_include}" "${KRR_BLENDER_SDK}/tbb/include"
		"${KRR_BLENDER_SDK}/MaterialX/include" "${KRR_BLENDER_SDK}/python/313/include")
	target_link_directories(krr_usd_sdk INTERFACE
		"${KRR_BLENDER_SDK}/python/313/libs" "${KRR_BLENDER_SDK}/tbb/lib")
	target_link_libraries(krr_usd_sdk INTERFACE "${KRR_BLENDER_SDK}/usd/lib/usd_ms.lib"
		"${KRR_BLENDER_SDK}/MaterialX/lib/MaterialXCore.lib"
		"${KRR_BLENDER_SDK}/MaterialX/lib/MaterialXFormat.lib")
	set(_materialx_libraries "${KRR_BLENDER_SDK}/MaterialX/libraries")
else()
	if(NOT KRR_USD_ROOT)
		if(NOT "$ENV{KRR_USD_ROOT}" STREQUAL "")
			set(KRR_USD_ROOT "$ENV{KRR_USD_ROOT}" CACHE PATH "Standalone Python-free OpenUSD SDK" FORCE)
		elseif(EXISTS "${KRR_RENDER_ROOT}/build/usd-sdk/standalone/install/include/pxr/pxr.h")
			set(KRR_USD_ROOT "${KRR_RENDER_ROOT}/build/usd-sdk/standalone/install" CACHE PATH "Standalone Python-free OpenUSD SDK" FORCE)
		endif()
	endif()
	if(NOT EXISTS "${KRR_USD_ROOT}/include/pxr/pxr.h")
		message(FATAL_ERROR "Set KRR_USD_ROOT to the Python-free SDK built by integrations/usd/build_sdk.py (selected: '${KRR_USD_ROOT}')")
	endif()
	file(READ "${KRR_USD_ROOT}/include/pxr/pxr.h" _usd_header)
	if(_usd_header MATCHES "#if 1[\r\n]+#define PXR_PYTHON_SUPPORT_ENABLED" OR _usd_header MATCHES "pxrBlender")
		message(FATAL_ERROR "Standalone USD requires a separate SDK built with Python support OFF")
	endif()
	list(PREPEND CMAKE_PREFIX_PATH "${KRR_USD_ROOT}")
	find_package(pxr CONFIG REQUIRED PATHS "${KRR_USD_ROOT}" NO_DEFAULT_PATH)
	if(NOT PXR_VERSION STREQUAL "2603")
		message(FATAL_ERROR "The standalone integration is validated against OpenUSD 26.03")
	endif()
	target_link_libraries(krr_usd_sdk INTERFACE usd_m MaterialXCore MaterialXFormat)
	set(_materialx_libraries "${KRR_USD_ROOT}/libraries")
endif()
target_include_directories(krr_usd_sdk INTERFACE "${KRR_RENDER_ROOT}/integrations")
target_compile_definitions(krr_usd_sdk INTERFACE NOMINMAX
	KRR_MATERIALX_STDLIB="${_materialx_libraries}")
