#pragma once

#define KRR_PROJECT_NAME "${CMAKE_PROJECT_NAME}"
#define KRR_PROJECT_DIR "${CMAKE_SOURCE_DIR}"
#define KRR_BUILD_TYPE "${CMAKE_BUILD_TYPE}"
#define KRR_VULKAN_ROOT "${KRR_VULKAN_ROOT}"
#define KRR_PYTORCH_ROOT "${KRR_PYTORCH_ROOT}"

#cmakedefine01	KRR_BUILD_STARLIGHT
#cmakedefine01	KRR_RENDER_SPECTRAL
#cmakedefine01  KRR_ENABLE_PYTORCH

#define KRR_ENABLE_PROFILE	1

#define KRR_N_SPECTRUM_SAMPLES	  4
#define KRR_CLIPSPACE_RIGHTHANDED 1
#define KRR_CLIPSPACE_Z_FROM_ZERO 1

#define KRR_DEFAULT_RND_SEED	7272
#define OPTIX_LOG_SIZE			4096