name: Auto-merge PRs

on: 
  pull_request:
    branches: [ hotfix ]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'cuteday'
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.DEPENDABOT_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash